name:                shell-runner
version:             0.1.0.0
github:              "ruzen42/shell-runner"
license:             BSD-3-Clause
author:              "Jaroslav Mihajlenko"
maintainer:          "malledeferlive@gmail.com"
copyright:           BSD-3-Clause

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            simple microservice for RuzenBot
category:            Web

description:         Please see the README on GitHub at <https://github.com/ruzen42/shell-runner#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp
- process
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  shell-runner-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - shell-runner
